version: "2"
services:
  antidote1:
    image: antidotedb/antidote
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
    ports:
      - "8087:8087"

  antidote2:
    image: antidotedb/antidote
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    ports:
      - "8088:8087"

  link:
    image: erlang:19
    volumes:
      - .:/code
    command: '/code/link.sh'
    links:
      - antidote1
      - antidote2
